/**
 * Abstract Event generated by simulator.
 */
export abstract class AppEvent {
}

/**
 * Cell has been filled with value event.
 */
export class CellFilledEvent extends AppEvent {
  constructor(private idx: number[], private value: number) {
    super();
  }

  public toString() {
    return 'Cell (' + this.idx[0] + ', ' + this.idx[1] + ', ' + this.idx[2] + ') filled with ' + this.value;
  }
}
